name: Build and Test
on:
    release:
        types: [created, published]
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
              python-version: '3.10'
        
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pyinstaller
        
        - name: Install X11 dependencies
          run: |
              sudo apt-get update
              sudo apt-get install -y libx11-dev libxtst-dev libxkbcommon-dev libxkbcommon-x11-dev xorg-dev
        
        - name: Build with PyInstaller
          run: |
              pyinstaller --onefile --name psp-mouse-injector \
                  --hidden-import pynput.keyboard._xorg \
                  --hidden-import pynput.mouse._xorg \
                  mohh1-mouse-injector.py
        
        - name: Upload Linux Build Artifact
          uses: actions/upload-artifact@v4
          with:
              name: psp-mouse-injector-linux
              path: dist/psp-mouse-injector
              if-no-files-found: error
        
        - name: Upload to Release
          if: github.event_name == 'release'
          uses: softprops/action-gh-release@v1
          with:
              files: dist/psp-mouse-injector
              tag_name: ${{ github.event.release.tag_name }}
