name: Build and Test
on:
    push:
        branches: [ main ]
        tags:
            - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
              python-version: '3.10'
        
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pyinstaller
        
        - name: Build with PyInstaller
          run: |
              pyinstaller --onefile --name psp-mouse-injector mohh1-mouse-injector.py
        
        - name: Upload Linux Build Artifact
          uses: actions/upload-artifact@v4
          with:
              name: psp-mouse-injector-linux
              path: dist/psp-mouse-injector
              if-no-files-found: error
        
        - name: Create Release
          id: create_release
          if: startsWith(github.ref, 'refs/tags/')
          uses: softprops/action-gh-release@v1
          with:
              files: dist/psp-mouse-injector
              draft: false
              prerelease: false
              generate_release_notes: true
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
