name: Build and Test
on:
    release:
        types: [created, published]
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:
jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
              python-version: '3.10'
        
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pyinstaller
        
        - name: Build with PyInstaller
          run: |
              pyinstaller --onefile --name psp-mouse-injector mohh1-mouse-injector.py
        
        - name: Upload Linux Build Artifact
          uses: actions/upload-artifact@v4
          with:
              name: psp-mouse-injector-linux
              path: dist/psp-mouse-injector
              if-no-files-found: error
        
        - name: Upload to Release
          if: github.event_name == 'release'
          uses: softprops/action-gh-release@v1
          with:
              files: dist/psp-mouse-injector
              tag_name: ${{ github.event.release.tag_name }}
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
